.build:
  stage: build
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_JOB_TOKEN" $CI_REGISTRY
  script:
    - |
      if [[ "$CI_COMMIT_BRANCH" == "$CI_DEFAULT_BRANCH" ]]; then
        tag=""
        echo "Running on default branch '$CI_DEFAULT_BRANCH': tag = 'latest'"
      else
        tag=":$CI_COMMIT_REF_SLUG"
        echo "Running on branch '$CI_COMMIT_BRANCH': tag = $tag"
      fi
    - docker build --pull -t "$CI_REGISTRY_IMAGE/optabroker-${DOCKER_IMAGE}${tag}" -f .docker/${DOCKER_FOLDER}/Dockerfile .
    - docker push "$CI_REGISTRY_IMAGE/optabroker-${DOCKER_IMAGE}${tag}"
  only:
    - master

build-optabroker-fpm:
  extends: .build
  variables:
    DOCKER_FOLDER: optabroker
    DOCKER_IMAGE: fpm

build-optabroker-nginx:
  extends: .build
  variables:
    DOCKER_FOLDER: web
    DOCKER_IMAGE: nginx
