version: "3.6"

networks:
    optabroker-network:
        name: optabroker-network
        external: true

services:
    optabroker:
        image: inkodus/optabroker:latest
        container_name: optabroker
        build:
            context: ./
            dockerfile: .docker/optabroker/local/Dockerfile
        volumes:
            - ./:/var/www/html
            - ./shared:/var/shared
            - ./xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
        environment:
            BASEDIR: /var/www/html
            COMPOSER_AUTH: '${COMPOSER_AUTH}'
            HOME: /var/www/html
            # look at .docker/web/nginx/conf.d/default.conf for optabroker.dv value
            PHP_IDE_CONFIG: 'serverName=optabroker.dv'
        #      CURRENT_UID: '${CURRENT_UID}'
        #      SYSTEM_UID: '${SYSTEM_UID}'
        #      SYSTEM_GID: '${SYSTEM_GID}'
        depends_on:
              - optabroker_db
        # user: ${CURRENT_UID}
        ports:
            - "5173:5173"
        networks:
            - optabroker-network
        extra_hosts:
            - host.docker.internal:host-gateway

    optabroker_db:
        container_name: optabroker_db
        image: mariadb:latest
        volumes:
            - ./.docker/db/storage/volumes/mysql:/var/lib/mysql
#            - ./.docker/db/resources/database_character_set.sh:/docker-entrypoint-initdb.d/database_character_set.sh
        environment:
            - MYSQL_ROOT_PASSWORD=optabrokerp
            - MYSQL_USER=optabroker
            - MYSQL_PASSWORD=optabroker
            - MYSQL_DATABASE=optabroker
            - TERM=dumb
        ports:
            - "23311:3306"
        networks:
            - optabroker-network

    optabroker_web:
        image: inkodus/optabroker_web:latest
        container_name: optabroker_web
        build:
            context: ./
            dockerfile: .docker/web/nginx/local/Dockerfile
        links:
            - optabroker:php_fpm
        ports:
            - "8080:80"
        environment:
            - BASEDIR=/var/www/html

        volumes:
            - ./.docker/web/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
            - ./:/var/www/html
            - ./shared:/var/shared

        networks:
            - optabroker-network

        depends_on:
            - optabroker
